---
# bring stack down
  - hosts: loadbalancer
    become: true
    tasks:
      - name: stop nginx
        service: name=nginx state=stopped
      -wait_for: port=80 state=drained
 
  - hosts: webserver
    become: true
    tasks:
      - name: stop apache2
        service: name=apache2 state=stopped
      -wait_for: port=80 state=stopped


# restart daatabase
  - hosts: database
    become: true
    tasks:
      - name: restart mysql
        service: name=mysql state=restarted
      -wait_for: host={{ansible_eth0.ipv4.address}}  port=3306 state=started

# start stack
  - hosts: webserver
    become: true
    tasks:
      - name: start apache2
        service: name=apache2 state=started
      -wait_for: port=80

  - hosts: loadbalancer
    become: true
    tasks:
      - name: start nginx
        service: name=nginx state=started
      -wait_for: port=80





